@extends('layouts.simple.master')
@section('title', 'Ionic Icons')

@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/vendors/ionic-icon.css')}}">
@endsection

@section('style')
@endsection

@section('breadcrumb-title')
<h3>Ionic Icon</h3>
@endsection

@section('breadcrumb-items')
<li class="breadcrumb-item">Icons</li>
<li class="breadcrumb-item active">Ionic Icon</li>
@endsection

@section('content')
<div class="container-fluid">
      <div class="row">
            <div class="col-sm-12">
                  <div class="card">
                        <div class="card-header">
                              <h5 class="m-b-0">ionic Icons</h5>
                        </div>
                        <div class="card-body">
                              <div class="row icon-lists">
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ionic"></i>ion-ionic</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-up-a"></i>ion-arrow-up-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-right-a"></i>ion-arrow-right-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-down-a"></i>ion-arrow-down-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-left-a"></i>ion-arrow-left-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-up-b"></i>ion-arrow-up-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-right-b"></i>ion-arrow-right-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-down-b"></i>ion-arrow-down-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-left-b"></i>ion-arrow-left-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-up-c"></i>ion-arrow-up-c</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-right-c"></i>ion-arrow-right-c</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-down-c"></i>ion-arrow-down-c</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-left-c"></i>ion-arrow-left-c</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-return-right"></i>ion-arrow-return-right</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-return-left"></i>ion-arrow-return-left</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-swap"></i>ion-arrow-swap</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-shrink"></i>ion-arrow-shrink</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-expand"></i>ion-arrow-expand</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-move"></i>ion-arrow-move</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-resize"></i>ion-arrow-resize</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chevron-up"></i>ion-chevron-up</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chevron-right"></i>ion-chevron-right</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chevron-down"></i>ion-chevron-down</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chevron-left"></i>ion-chevron-left</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-navicon-round"></i>ion-navicon-round</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-navicon"></i>ion-navicon</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-drag"></i>ion-drag</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-log-in"></i>ion-log-in</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-log-out"></i>ion-log-out</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-checkmark-round"></i>ion-checkmark-round</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-checkmark"></i>ion-checkmark</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-checkmark-circled"></i>ion-checkmark-circled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-close-round"></i>ion-close-round</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-close"></i>ion-close</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-close-circled"></i>ion-close-circled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-plus-round"></i>ion-plus-round</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-plus"></i>ion-plus</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-plus-circled"></i>ion-plus-circled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-minus-round"></i>ion-minus-round</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-minus"></i>ion-minus</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-minus-circled"></i>ion-minus-circled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-information"></i>ion-information</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-information-circled"></i>ion-information-circled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-help"></i>ion-help</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-help-circled"></i>ion-help-circled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-backspace-outline"></i>ion-backspace-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-backspace"></i>ion-backspace</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-help-buoy"></i>ion-help-buoy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-asterisk"></i>ion-asterisk</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-alert"></i>ion-alert</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-alert-circled"></i>ion-alert-circled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-refresh"></i>ion-refresh</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-loop"></i>ion-loop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-shuffle"></i>ion-shuffle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-home"></i>ion-home</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-search"></i>ion-search</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-flag"></i>ion-flag</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-star"></i>ion-star</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-heart"></i>ion-heart</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-heart-broken"></i>ion-heart-broken</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-gear-a"></i>ion-gear-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-gear-b"></i>ion-gear-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-toggle-filled"></i>ion-toggle-filled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-toggle"></i>ion-toggle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-settings"></i>ion-settings</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-wrench"></i>ion-wrench</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-hammer"></i>ion-hammer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-edit"></i>ion-edit</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-trash-a"></i>ion-trash-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-trash-b"></i>ion-trash-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-document"></i>ion-document</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-document-text"></i>ion-document-text</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-clipboard"></i>ion-clipboard</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-scissors"></i>ion-scissors</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-funnel"></i>ion-funnel</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-bookmark"></i>ion-bookmark</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-email"></i>ion-email</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-email-unread"></i>ion-email-unread</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-folder"></i>ion-folder</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-filing"></i>ion-filing</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-archive"></i>ion-archive</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-reply"></i>ion-reply</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-reply-all"></i>ion-reply-all</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-forward"></i>ion-forward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-share"></i>ion-share</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-paper-airplane"></i>ion-paper-airplane</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-link"></i>ion-link</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-paperclip"></i>ion-paperclip</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-compose"></i>ion-compose</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-briefcase"></i>ion-briefcase</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-medkit"></i>ion-medkit</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-at"></i>ion-at</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pound"></i>ion-pound</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-quote"></i>ion-quote</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-cloud"></i>ion-cloud</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-upload"></i>ion-upload</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-more"></i>ion-more</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-grid"></i>ion-grid</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-calendar"></i>ion-calendar</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-clock"></i>ion-clock</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-compass"></i>ion-compass</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pinpoint"></i>ion-pinpoint</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pin"></i>ion-pin</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-navigate"></i>ion-navigate</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-location"></i>ion-location</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-map"></i>ion-map</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-lock-combination"></i>ion-lock-combination</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-locked"></i>ion-locked</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-unlocked"></i>ion-unlocked</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-key"></i>ion-key</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-graph-up-right"></i>ion-arrow-graph-up-right</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-graph-down-right"></i>ion-arrow-graph-down-right</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-graph-up-left"></i>ion-arrow-graph-up-left</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-arrow-graph-down-left"></i>ion-arrow-graph-down-left</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-stats-bars"></i>ion-stats-bars</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-connection-bars"></i>ion-connection-bars</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pie-graph"></i>ion-pie-graph</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chatbubble"></i>ion-chatbubble</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chatbubble-working"></i>ion-chatbubble-working</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chatbubbles"></i>ion-chatbubbles</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chatbox"></i>ion-chatbox</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chatbox-working"></i>ion-chatbox-working</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-chatboxes"></i>ion-chatboxes</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-person"></i>ion-person</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-person-add"></i>ion-person-add</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-person-stalker"></i>ion-person-stalker</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-woman"></i>ion-woman</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-man"></i>ion-man</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-female"></i>ion-female</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-male"></i>ion-male</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-transgender"></i>ion-transgender</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-fork"></i>ion-fork</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-knife"></i>ion-knife</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-spoon"></i>ion-spoon</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-soup-can-outline"></i>ion-soup-can-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-soup-can"></i>ion-soup-can</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-beer"></i>ion-beer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-wineglass"></i>ion-wineglass</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-coffee"></i>ion-coffee</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-icecream"></i>ion-icecream</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pizza"></i>ion-pizza</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-power"></i>ion-power</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-mouse"></i>ion-mouse</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-battery-full"></i>ion-battery-full</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-battery-half"></i>ion-battery-half</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-battery-low"></i>ion-battery-low</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-battery-empty"></i>ion-battery-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-battery-charging"></i>ion-battery-charging</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-wifi"></i>ion-wifi</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-bluetooth"></i>ion-bluetooth</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-calculator"></i>ion-calculator</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-camera"></i>ion-camera</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-eye"></i>ion-eye</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-eye-disabled"></i>ion-eye-disabled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-flash"></i>ion-flash</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-flash-off"></i>ion-flash-off</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-qr-scanner"></i>ion-qr-scanner</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-image"></i>ion-image</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-images"></i>ion-images</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-wand"></i>ion-wand</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-contrast"></i>ion-contrast</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-aperture"></i>ion-aperture</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-crop"></i>ion-crop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-easel"></i>ion-easel</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-paintbrush"></i>ion-paintbrush</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-paintbucket"></i>ion-paintbucket</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-monitor"></i>ion-monitor</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-laptop"></i>ion-laptop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ipad"></i>ion-ipad</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-iphone"></i>ion-iphone</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ipod"></i>ion-ipod</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-printer"></i>ion-printer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-usb"></i>ion-usb</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-outlet"></i>ion-outlet</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-bug"></i>ion-bug</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-code"></i>ion-code</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-code-working"></i>ion-code-working</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-code-download"></i>ion-code-download</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-fork-repo"></i>ion-fork-repo</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-network"></i>ion-network</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pull-request"></i>ion-pull-request</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-merge"></i>ion-merge</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-xbox"></i>ion-xbox</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-playstation"></i>ion-playstation</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-steam"></i>ion-steam</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-closed-captioning"></i>ion-closed-captioning</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-videocamera"></i>ion-videocamera</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-film-marker"></i>ion-film-marker</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-disc"></i>ion-disc</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-headphone"></i>ion-headphone</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-music-note"></i>ion-music-note</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-radio-waves"></i>ion-radio-waves</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-speakerphone"></i>ion-speakerphone</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-mic-a"></i>ion-mic-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-mic-b"></i>ion-mic-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-mic-c"></i>ion-mic-c</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-volume-high"></i>ion-volume-high</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-volume-medium"></i>ion-volume-medium</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-volume-low"></i>ion-volume-low</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-volume-mute"></i>ion-volume-mute</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-levels"></i>ion-levels</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-play"></i>ion-play</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pause"></i>ion-pause</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-stop"></i>ion-stop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-record"></i>ion-record</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-skip-forward"></i>ion-skip-forward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-skip-backward"></i>ion-skip-backward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-eject"></i>ion-eject</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-bag"></i>ion-bag</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-card"></i>ion-card</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-cash"></i>ion-cash</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pricetag"></i>ion-pricetag</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-pricetags"></i>ion-pricetags</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-thumbsup"></i>ion-thumbsup</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-thumbsdown"></i>ion-thumbsdown</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-happy-outline"></i>ion-happy-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-happy"></i>ion-happy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-sad-outline"></i>ion-sad-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-sad"></i>ion-sad</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-bowtie"></i>ion-bowtie</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-tshirt-outline"></i>ion-tshirt-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-tshirt"></i>ion-tshirt</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-trophy"></i>ion-trophy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-podium"></i>ion-podium</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ribbon-a"></i>ion-ribbon-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ribbon-b"></i>ion-ribbon-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-university"></i>ion-university</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-magnet"></i>ion-magnet</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-beaker"></i>ion-beaker</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-erlenmeyer-flask"></i>ion-erlenmeyer-flask</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-egg"></i>ion-egg</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-earth"></i>ion-earth</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-planet"></i>ion-planet</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-lightbulb"></i>ion-lightbulb</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-cube"></i>ion-cube</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-leaf"></i>ion-leaf</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-waterdrop"></i>ion-waterdrop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-flame"></i>ion-flame</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-fireball"></i>ion-fireball</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-bonfire"></i>ion-bonfire</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-umbrella"></i>ion-umbrella</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-nuclear"></i>ion-nuclear</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-no-smoking"></i>ion-no-smoking</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-thermometer"></i>ion-thermometer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-speedometer"></i>ion-speedometer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-model-s"></i>ion-model-s</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-plane"></i>ion-plane</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-jet"></i>ion-jet</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-load-a"></i>ion-load-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-load-b"></i>ion-load-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-load-c"></i>ion-load-c</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-load-d"></i>ion-load-d</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-ionic-outline"></i>ion-ios-ionic-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-back"></i>ion-ios-arrow-back</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-forward"></i>ion-ios-arrow-forward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-up"></i>ion-ios-arrow-up</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-right"></i>ion-ios-arrow-right</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-down"></i>ion-ios-arrow-down</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-left"></i>ion-ios-arrow-left</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-thin-up"></i>ion-ios-arrow-thin-up</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-thin-right"></i>ion-ios-arrow-thin-right</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-thin-down"></i>ion-ios-arrow-thin-down</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-arrow-thin-left"></i>ion-ios-arrow-thin-left</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-circle-filled"></i>ion-ios-circle-filled</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-circle-outline"></i>ion-ios-circle-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-checkmark-empty"></i>ion-ios-checkmark-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-checkmark-outline"></i>ion-ios-checkmark-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-checkmark"></i>ion-ios-checkmark</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-plus-empty"></i>ion-ios-plus-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-plus-outline"></i>ion-ios-plus-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-plus"></i>ion-ios-plus</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-close-empty"></i>ion-ios-close-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-close-outline"></i>ion-ios-close-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-close"></i>ion-ios-close</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-minus-empty"></i>ion-ios-minus-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-minus-outline"></i>ion-ios-minus-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-minus"></i>ion-ios-minus</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-information-empty"></i>ion-ios-information-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-information-outline"></i>ion-ios-information-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-information"></i>ion-ios-information</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-help-empty"></i>ion-ios-help-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-help-outline"></i>ion-ios-help-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-help"></i>ion-ios-help</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-search"></i>ion-ios-search</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-search-strong"></i>ion-ios-search-strong</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-star"></i>ion-ios-star</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-star-half"></i>ion-ios-star-half</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-star-outline"></i>ion-ios-star-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-heart"></i>ion-ios-heart</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-heart-outline"></i>ion-ios-heart-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-more"></i>ion-ios-more</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-more-outline"></i>ion-ios-more-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-home"></i>ion-ios-home</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-home-outline"></i>ion-ios-home-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloud"></i>ion-ios-cloud</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloud-outline"></i>ion-ios-cloud-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloud-upload"></i>ion-ios-cloud-upload</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloud-upload-outline"></i>ion-ios-cloud-upload-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloud-download"></i>ion-ios-cloud-download</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloud-download-outline"></i>ion-ios-cloud-download-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-upload"></i>ion-ios-upload</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-upload-outline"></i>ion-ios-upload-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-download"></i>ion-ios-download</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-download-outline"></i>ion-ios-download-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-refresh"></i>ion-ios-refresh</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-refresh-outline"></i>ion-ios-refresh-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-refresh-empty"></i>ion-ios-refresh-empty</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-reload"></i>ion-ios-reload</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-loop-strong"></i>ion-ios-loop-strong</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-loop"></i>ion-ios-loop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-bookmarks"></i>ion-ios-bookmarks</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-bookmarks-outline"></i>ion-ios-bookmarks-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-book"></i>ion-ios-book</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-book-outline"></i>ion-ios-book-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flag"></i>ion-ios-flag</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flag-outline"></i>ion-ios-flag-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-glasses"></i>ion-ios-glasses</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-glasses-outline"></i>ion-ios-glasses-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-browsers"></i>ion-ios-browsers</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-browsers-outline"></i>ion-ios-browsers-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-at"></i>ion-ios-at</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-at-outline"></i>ion-ios-at-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pricetag"></i>ion-ios-pricetag</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pricetag-outline"></i>ion-ios-pricetag-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pricetags"></i>ion-ios-pricetags</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pricetags-outline"></i>ion-ios-pricetags-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cart"></i>ion-ios-cart</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cart-outline"></i>ion-ios-cart-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-chatboxes"></i>ion-ios-chatboxes</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-chatboxes-outline"></i>ion-ios-chatboxes-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-chatbubble"></i>ion-ios-chatbubble</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-chatbubble-outline"></i>ion-ios-chatbubble-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cog"></i>ion-ios-cog</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cog-outline"></i>ion-ios-cog-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-gear"></i>ion-ios-gear</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-gear-outline"></i>ion-ios-gear-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-settings"></i>ion-ios-settings</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-settings-strong"></i>ion-ios-settings-strong</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-toggle"></i>ion-ios-toggle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-toggle-outline"></i>ion-ios-toggle-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-analytics"></i>ion-ios-analytics</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-analytics-outline"></i>ion-ios-analytics-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pie"></i>ion-ios-pie</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pie-outline"></i>ion-ios-pie-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pulse"></i>ion-ios-pulse</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pulse-strong"></i>ion-ios-pulse-strong</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-filing"></i>ion-ios-filing</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-filing-outline"></i>ion-ios-filing-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-box"></i>ion-ios-box</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-box-outline"></i>ion-ios-box-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-compose"></i>ion-ios-compose</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-compose-outline"></i>ion-ios-compose-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-trash"></i>ion-ios-trash</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-trash-outline"></i>ion-ios-trash-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-copy"></i>ion-ios-copy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-copy-outline"></i>ion-ios-copy-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-email"></i>ion-ios-email</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-email-outline"></i>ion-ios-email-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-undo"></i>ion-ios-undo</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-undo-outline"></i>ion-ios-undo-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-redo"></i>ion-ios-redo</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-redo-outline"></i>ion-ios-redo-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-paperplane"></i>ion-ios-paperplane</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-paperplane-outline"></i>ion-ios-paperplane-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-folder"></i>ion-ios-folder</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-folder-outline"></i>ion-ios-folder-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-paper"></i>ion-ios-paper</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-paper-outline"></i>ion-ios-paper-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-list"></i>ion-ios-list</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-list-outline"></i>ion-ios-list-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-world"></i>ion-ios-world</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-world-outline"></i>ion-ios-world-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-alarm"></i>ion-ios-alarm</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-alarm-outline"></i>ion-ios-alarm-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-speedometer"></i>ion-ios-speedometer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-speedometer-outline"></i>ion-ios-speedometer-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-stopwatch"></i>ion-ios-stopwatch</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-stopwatch-outline"></i>ion-ios-stopwatch-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-timer"></i>ion-ios-timer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-timer-outline"></i>ion-ios-timer-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-clock"></i>ion-ios-clock</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-clock-outline"></i>ion-ios-clock-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-time"></i>ion-ios-time</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-time-outline"></i>ion-ios-time-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-calendar"></i>ion-ios-calendar</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-calendar-outline"></i>ion-ios-calendar-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-photos"></i>ion-ios-photos</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-photos-outline"></i>ion-ios-photos-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-albums"></i>ion-ios-albums</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-albums-outline"></i>ion-ios-albums-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-camera"></i>ion-ios-camera</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-camera-outline"></i>ion-ios-camera-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-reverse-camera"></i>ion-ios-reverse-camera</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-reverse-camera-outline"></i>ion-ios-reverse-camera-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-eye"></i>ion-ios-eye</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-eye-outline"></i>ion-ios-eye-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-bolt"></i>ion-ios-bolt</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-bolt-outline"></i>ion-ios-bolt-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-color-wand"></i>ion-ios-color-wand</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-color-wand-outline"></i>ion-ios-color-wand-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-color-filter"></i>ion-ios-color-filter</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-color-filter-outline"></i>ion-ios-color-filter-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-grid-view"></i>ion-ios-grid-view</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-grid-view-outline"></i>ion-ios-grid-view-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-crop-strong"></i>ion-ios-crop-strong</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-crop"></i>ion-ios-crop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-barcode"></i>ion-ios-barcode</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-barcode-outline"></i>ion-ios-barcode-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-briefcase"></i>ion-ios-briefcase</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-briefcase-outline"></i>ion-ios-briefcase-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-medkit"></i>ion-ios-medkit</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-medkit-outline"></i>ion-ios-medkit-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-medical"></i>ion-ios-medical</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-medical-outline"></i>ion-ios-medical-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-infinite"></i>ion-ios-infinite</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-infinite-outline"></i>ion-ios-infinite-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-calculator"></i>ion-ios-calculator</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-calculator-outline"></i>ion-ios-calculator-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-keypad"></i>ion-ios-keypad</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-keypad-outline"></i>ion-ios-keypad-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-telephone"></i>ion-ios-telephone</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-telephone-outline"></i>ion-ios-telephone-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-drag"></i>ion-ios-drag</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-location"></i>ion-ios-location</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-location-outline"></i>ion-ios-location-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-navigate"></i>ion-ios-navigate</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-navigate-outline"></i>ion-ios-navigate-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-locked"></i>ion-ios-locked</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-locked-outline"></i>ion-ios-locked-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-unlocked"></i>ion-ios-unlocked</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-unlocked-outline"></i>ion-ios-unlocked-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-monitor"></i>ion-ios-monitor</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-monitor-outline"></i>ion-ios-monitor-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-printer"></i>ion-ios-printer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-printer-outline"></i>ion-ios-printer-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-game-controller-a"></i>ion-ios-game-controller-a</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-game-controller-a-outline"></i>ion-ios-game-controller-a-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-game-controller-b"></i>ion-ios-game-controller-b</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-game-controller-b-outline"></i>ion-ios-game-controller-b-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-americanfootball"></i>ion-ios-americanfootball</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-americanfootball-outline"></i>ion-ios-americanfootball-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-baseball"></i>ion-ios-baseball</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-baseball-outline"></i>ion-ios-baseball-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-basketball"></i>ion-ios-basketball</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-basketball-outline"></i>ion-ios-basketball-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-tennisball"></i>ion-ios-tennisball</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-tennisball-outline"></i>ion-ios-tennisball-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-football"></i>ion-ios-football</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-football-outline"></i>ion-ios-football-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-body"></i>ion-ios-body</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-body-outline"></i>ion-ios-body-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-person"></i>ion-ios-person</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-person-outline"></i>ion-ios-person-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-personadd"></i>ion-ios-personadd</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-personadd-outline"></i>ion-ios-personadd-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-people"></i>ion-ios-people</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-people-outline"></i>ion-ios-people-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-musical-notes"></i>ion-ios-musical-notes</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-musical-note"></i>ion-ios-musical-note</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-bell"></i>ion-ios-bell</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-bell-outline"></i>ion-ios-bell-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-mic"></i>ion-ios-mic</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-mic-outline"></i>ion-ios-mic-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-mic-off"></i>ion-ios-mic-off</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-volume-high"></i>ion-ios-volume-high</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-volume-low"></i>ion-ios-volume-low</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-play"></i>ion-ios-play</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-play-outline"></i>ion-ios-play-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pause"></i>ion-ios-pause</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pause-outline"></i>ion-ios-pause-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-recording"></i>ion-ios-recording</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-recording-outline"></i>ion-ios-recording-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-fastforward"></i>ion-ios-fastforward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-fastforward-outline"></i>ion-ios-fastforward-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-rewind"></i>ion-ios-rewind</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-rewind-outline"></i>ion-ios-rewind-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-skipbackward"></i>ion-ios-skipbackward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-skipbackward-outline"></i>ion-ios-skipbackward-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-skipforward"></i>ion-ios-skipforward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-skipforward-outline"></i>ion-ios-skipforward-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-shuffle-strong"></i>ion-ios-shuffle-strong</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-shuffle"></i>ion-ios-shuffle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-videocam"></i>ion-ios-videocam</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-videocam-outline"></i>ion-ios-videocam-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-film"></i>ion-ios-film</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-film-outline"></i>ion-ios-film-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flask"></i>ion-ios-flask</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flask-outline"></i>ion-ios-flask-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-lightbulb"></i>ion-ios-lightbulb</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-lightbulb-outline"></i>ion-ios-lightbulb-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-wineglass"></i>ion-ios-wineglass</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-wineglass-outline"></i>ion-ios-wineglass-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pint"></i>ion-ios-pint</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-pint-outline"></i>ion-ios-pint-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-nutrition"></i>ion-ios-nutrition</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-nutrition-outline"></i>ion-ios-nutrition-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flower"></i>ion-ios-flower</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flower-outline"></i>ion-ios-flower-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-rose"></i>ion-ios-rose</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-rose-outline"></i>ion-ios-rose-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-paw"></i>ion-ios-paw</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-paw-outline"></i>ion-ios-paw-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flame"></i>ion-ios-flame</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-flame-outline"></i>ion-ios-flame-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-sunny"></i>ion-ios-sunny</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-sunny-outline"></i>ion-ios-sunny-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-partlysunny"></i>ion-ios-partlysunny</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-partlysunny-outline"></i>ion-ios-partlysunny-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloudy"></i>ion-ios-cloudy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloudy-outline"></i>ion-ios-cloudy-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-rainy"></i>ion-ios-rainy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-rainy-outline"></i>ion-ios-rainy-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-thunderstorm"></i>ion-ios-thunderstorm</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-thunderstorm-outline"></i>ion-ios-thunderstorm-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-snowy"></i>ion-ios-snowy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-moon"></i>ion-ios-moon</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-moon-outline"></i>ion-ios-moon-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloudy-night"></i>ion-ios-cloudy-night</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-ios-cloudy-night-outline"></i>ion-ios-cloudy-night-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-up"></i>ion-android-arrow-up</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-forward"></i>ion-android-arrow-forward</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-down"></i>ion-android-arrow-down</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-back"></i>ion-android-arrow-back</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropup"></i>ion-android-arrow-dropup</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropup-circle"></i>ion-android-arrow-dropup-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropright"></i>ion-android-arrow-dropright</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropright-circle"></i>ion-android-arrow-dropright-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropdown"></i>ion-android-arrow-dropdown</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropdown-circle"></i>ion-android-arrow-dropdown-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropleft"></i>ion-android-arrow-dropleft</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-arrow-dropleft-circle"></i>ion-android-arrow-dropleft-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-add"></i>ion-android-add</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-add-circle"></i>ion-android-add-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-remove"></i>ion-android-remove</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-remove-circle"></i>ion-android-remove-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-close"></i>ion-android-close</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-cancel"></i>ion-android-cancel</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-radio-button-off"></i>ion-android-radio-button-off</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-radio-button-on"></i>ion-android-radio-button-on</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-checkmark-circle"></i>ion-android-checkmark-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-checkbox-outline-blank"></i>ion-android-checkbox-outline-blank</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-checkbox-outline"></i>ion-android-checkbox-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-checkbox-blank"></i>ion-android-checkbox-blank</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-checkbox"></i>ion-android-checkbox</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-done"></i>ion-android-done</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-done-all"></i>ion-android-done-all</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-menu"></i>ion-android-menu</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-more-horizontal"></i>ion-android-more-horizontal</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-more-vertical"></i>ion-android-more-vertical</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-refresh"></i>ion-android-refresh</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-sync"></i>ion-android-sync</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-wifi"></i>ion-android-wifi</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-call"></i>ion-android-call</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-apps"></i>ion-android-apps</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-settings"></i>ion-android-settings</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-options"></i>ion-android-options</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-funnel"></i>ion-android-funnel</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-search"></i>ion-android-search</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-home"></i>ion-android-home</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-cloud-outline"></i>ion-android-cloud-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-cloud"></i>ion-android-cloud</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-download"></i>ion-android-download</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-upload"></i>ion-android-upload</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-cloud-done"></i>ion-android-cloud-done</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-cloud-circle"></i>ion-android-cloud-circle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-favorite-outline"></i>ion-android-favorite-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-favorite"></i>ion-android-favorite</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-star-outline"></i>ion-android-star-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-star-half"></i>ion-android-star-half</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-star"></i>ion-android-star</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-calendar"></i>ion-android-calendar</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-alarm-clock"></i>ion-android-alarm-clock</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-time"></i>ion-android-time</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-stopwatch"></i>ion-android-stopwatch</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-watch"></i>ion-android-watch</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-locate"></i>ion-android-locate</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-navigate"></i>ion-android-navigate</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-pin"></i>ion-android-pin</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-compass"></i>ion-android-compass</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-map"></i>ion-android-map</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-walk"></i>ion-android-walk</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-bicycle"></i>ion-android-bicycle</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-car"></i>ion-android-car</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-bus"></i>ion-android-bus</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-subway"></i>ion-android-subway</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-train"></i>ion-android-train</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-boat"></i>ion-android-boat</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-plane"></i>ion-android-plane</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-restaurant"></i>ion-android-restaurant</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-bar"></i>ion-android-bar</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-cart"></i>ion-android-cart</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-camera"></i>ion-android-camera</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-image"></i>ion-android-image</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-film"></i>ion-android-film</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-color-palette"></i>ion-android-color-palette</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-create"></i>ion-android-create</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-mail"></i>ion-android-mail</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-drafts"></i>ion-android-drafts</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-send"></i>ion-android-send</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-archive"></i>ion-android-archive</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-delete"></i>ion-android-delete</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-attach"></i>ion-android-attach</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-share"></i>ion-android-share</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-share-alt"></i>ion-android-share-alt</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-bookmark"></i>ion-android-bookmark</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-document"></i>ion-android-document</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-clipboard"></i>ion-android-clipboard</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-list"></i>ion-android-list</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-folder-open"></i>ion-android-folder-open</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-folder"></i>ion-android-folder</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-print"></i>ion-android-print</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-open"></i>ion-android-open</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-exit"></i>ion-android-exit</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-contract"></i>ion-android-contract</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-expand"></i>ion-android-expand</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-globe"></i>ion-android-globe</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-chat"></i>ion-android-chat</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-textsms"></i>ion-android-textsms</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-hangout"></i>ion-android-hangout</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-happy"></i>ion-android-happy</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-sad"></i>ion-android-sad</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-person"></i>ion-android-person</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-people"></i>ion-android-people</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-person-add"></i>ion-android-person-add</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-contact"></i>ion-android-contact</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-contacts"></i>ion-android-contacts</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-playstore"></i>ion-android-playstore</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-lock"></i>ion-android-lock</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-unlock"></i>ion-android-unlock</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-microphone"></i>ion-android-microphone</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-microphone-off"></i>ion-android-microphone-off</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-notifications-none"></i>ion-android-notifications-none</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-notifications"></i>ion-android-notifications</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-notifications-off"></i>ion-android-notifications-off</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-volume-mute"></i>ion-android-volume-mute</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-volume-down"></i>ion-android-volume-down</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-volume-up"></i>ion-android-volume-up</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-volume-off"></i>ion-android-volume-off</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-hand"></i>ion-android-hand</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-desktop"></i>ion-android-desktop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-laptop"></i>ion-android-laptop</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-phone-portrait"></i>ion-android-phone-portrait</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-phone-landscape"></i>ion-android-phone-landscape</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-bulb"></i>ion-android-bulb</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-sunny"></i>ion-android-sunny</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-alert"></i>ion-android-alert</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-android-warning"></i>ion-android-warning</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-twitter"></i>ion-social-twitter</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-twitter-outline"></i>ion-social-twitter-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-facebook"></i>ion-social-facebook</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-facebook-outline"></i>ion-social-facebook-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-googleplus"></i>ion-social-googleplus</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-googleplus-outline"></i>ion-social-googleplus-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-google"></i>ion-social-google</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-google-outline"></i>ion-social-google-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-dribbble"></i>ion-social-dribbble</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-dribbble-outline"></i>ion-social-dribbble-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-octocat"></i>ion-social-octocat</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-github"></i>ion-social-github</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-github-outline"></i>ion-social-github-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-instagram"></i>ion-social-instagram</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-instagram-outline"></i>ion-social-instagram-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-whatsapp"></i>ion-social-whatsapp</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-whatsapp-outline"></i>ion-social-whatsapp-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-snapchat"></i>ion-social-snapchat</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-snapchat-outline"></i>ion-social-snapchat-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-foursquare"></i>ion-social-foursquare</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-foursquare-outline"></i>ion-social-foursquare-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-pinterest"></i>ion-social-pinterest</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-pinterest-outline"></i>ion-social-pinterest-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-rss"></i>ion-social-rss</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-rss-outline"></i>ion-social-rss-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-tumblr"></i>ion-social-tumblr</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-tumblr-outline"></i>ion-social-tumblr-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-wordpress"></i>ion-social-wordpress</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-wordpress-outline"></i>ion-social-wordpress-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-reddit"></i>ion-social-reddit</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-reddit-outline"></i>ion-social-reddit-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-hackernews"></i>ion-social-hackernews</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-hackernews-outline"></i>ion-social-hackernews-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-designernews"></i>ion-social-designernews</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-designernews-outline"></i>ion-social-designernews-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-yahoo"></i>ion-social-yahoo</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-yahoo-outline"></i>ion-social-yahoo-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-buffer"></i>ion-social-buffer</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-buffer-outline"></i>ion-social-buffer-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-skype"></i>ion-social-skype</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-skype-outline"></i>ion-social-skype-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-linkedin"></i>ion-social-linkedin</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-linkedin-outline"></i>ion-social-linkedin-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-vimeo"></i>ion-social-vimeo</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-vimeo-outline"></i>ion-social-vimeo-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-twitch"></i>ion-social-twitch</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-twitch-outline"></i>ion-social-twitch-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-youtube"></i>ion-social-youtube</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-youtube-outline"></i>ion-social-youtube-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-dropbox"></i>ion-social-dropbox</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-dropbox-outline"></i>ion-social-dropbox-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-apple"></i>ion-social-apple</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-apple-outline"></i>ion-social-apple-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-android"></i>ion-social-android</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-android-outline"></i>ion-social-android-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-windows"></i>ion-social-windows</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-windows-outline"></i>ion-social-windows-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-html5"></i>ion-social-html5</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-html5-outline"></i>ion-social-html5-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-css3"></i>ion-social-css3</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-css3-outline"></i>ion-social-css3-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-javascript"></i>ion-social-javascript</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-javascript-outline"></i>ion-social-javascript-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-angular"></i>ion-social-angular</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-angular-outline"></i>ion-social-angular-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-nodejs"></i>ion-social-nodejs</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-sass"></i>ion-social-sass</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-python"></i>ion-social-python</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-chrome"></i>ion-social-chrome</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-chrome-outline"></i>ion-social-chrome-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-codepen"></i>ion-social-codepen</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-codepen-outline"></i>ion-social-codepen-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-markdown"></i>ion-social-markdown</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-tux"></i>ion-social-tux</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-freebsd-devil"></i>ion-social-freebsd-devil</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-usd"></i>ion-social-usd</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-usd-outline"></i>ion-social-usd-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-bitcoin"></i>ion-social-bitcoin</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-bitcoin-outline"></i>ion-social-bitcoin-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-yen"></i>ion-social-yen</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-yen-outline"></i>ion-social-yen-outline</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-euro"></i>ion-social-euro</div>
                                    <div class="col-lg-4 col-sm-6"><i class="ion ion-social-euro-outline"></i>ion-social-euro-outline</div>
                              </div>
                        </div>
                  </div>
            </div>
      </div>
</div>
<div class="icon-hover-bottom p-fixed fa-fa-icon-show-div">
      <div class="container-fluid">
            <div class="row">
                  <div class="icon-popup">
                        <div class="close-icon"><i class="icofont icofont-close"></i></div>
                        <div class="icon-first"><i class="fa-2x" id="icon_main"></i></div>
                        <div class="icon-class">
                              <label class="icon-title">Class</label><span id="fclass1"></span>
                        </div>
                        <div class="icon-last icon-last">
                              <label class="icon-title">Markup</label>
                              <div class="form-inline">
                                    <div class="mb-3">
                                          <input class="inp-val form-control m-r-10" id="input_copy" type="text" value="" readonly="readonly">
                                          <button class="btn btn-primary notification" onclick="myFunction()">Copy text</button>
                                    </div>
                              </div>
                        </div>
                  </div>
            </div>
      </div>
</div>
@endsection

@section('script')
<script src="{{asset('assets/js/notify/bootstrap-notify.min.js')}}"></script>
<script src="{{asset('assets/js/icons/icons-notify.js')}}"></script>
<script src="{{asset('assets/js/icons/icon-clipart.js')}}"></script>
@endsection